version: '3.9'

services:
  http-server:
    container_name: http-server
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-db:5432/postgres"
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: postgres-db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}